#!/bin/sh

# Shell runner for Go commands
#
# Run by BBEdit scripts with BB_DOC_PATH set to the document

# Determine Go path
gopath() {
    local wspath=$(pwd)
    while [[ "$wspath" != "" ]] && ! [[ -d "$wspath/bin" && -d "$wspath/pkg" && -d "$wspath/src" ]]; do
        wspath=${wspath%/*}
    done
    echo "$wspath"
}

# Verify Go is installed
if which go &>/dev/null; then
	GOROOT=`go env GOROOT`
else
	echo "Go is not installed" >&2
	exit -1
fi

# Check that document was provided
if [ -z "$BB_DOC_PATH" ]; then
	echo "Document missing" >&2
	exit 1
fi

cd $(dirname "${BB_DOC_PATH}")

# Set PATH and GOPATH for workspace
export PATH=${GOROOT}:${PATH}
export GOPATH=$(gopath)

# Run command
$*
