#!/bin/sh

#
# Shell runner for Go commands
#
# Assumed to be run by BBEdit scripts with BB_DOC_PATH set to the document

# Add gows to shell environment
source "$(dirname "$0")/gows"

# Verify Go is installed
if which go &>/dev/null; then
	GOROOT=`go env GOROOT`
else
	echo "Go is not installed" >&2
	exit -1
fi

# Add Go to the path
export PATH=${GOROOT}:${PATH}

# Check that document was provided
if [ -z "$BB_DOC_PATH" ]
then
	echo "Document missing" >&2
	exit 1
fi

cd $(dirname "$BB_DOC_PATH")
GO15VENDOREXPERIMENT=1 gows run $*
