#!/bin/sh

gorunner="$(dirname "$0")/../Resources/gorunner"
goresults="$(dirname "$0")/../Resources/show_results.applescript"

# Expect BB_DOC_LANGUAGE, BB_DOC_MODE, BB_DOC_NAME, BB_DOC_PATH

# On save, run goimports, golint, go vet

(
    "$gorunner" goimports -w "$BB_DOC_PATH"
    "$gorunner" golint "$BB_DOC_PATH"
#     "$gorunner" go vet "$BB_DOC_PATH"
)
