#!/bin/sh

SCRIPT_PATH="${BASH_SOURCE[0]}"
source "`dirname "${SCRIPT_PATH}"`/upsearch"

# Execute go command from go path root using pkg path
CMD=$1
DOC=$2
FLAGS=$3
ARGS=
DOC_PATH=`dirname ${DOC}`
GOPKGROOT=`upsearch $DOC_PATH src`
PKG_PATH=`echo ${DOC_PATH#$GOPKGROOT/src/}`

if [[ "$CMD" == "run" ]]; then
    ARGS=${DOC}
else
    ARGS=${PKG_PATH}
fi

# Run go tool
cd $GOPKGROOT
GOPATH=$GOPKGROOT go ${CMD} ${FLAGS} ${ARGS}
