#!/bin/sh

#
# Shell runner for Go commands
#
# Assumed to be run by BBEdit scripts with BB_DOC_PATH set to the document

# Add goenv to shell environment
source "$(dirname "$0")/goenv"

# Add Go to the path
if [ -d /usr/local/go ]
then
	export PATH=/usr/local/go/bin:${PATH}
elif [ -d /opt/go ]
then
	export PATH=/opt/go/bin:${PATH}
else
	echo "Go is not installed" >&2
	exit -1
fi 

# Check that document was provided
if [ -z "$BB_DOC_PATH" ]
then
	echo "Document missing" >&2
	exit 1
fi

cd $(dirname "$BB_DOC_PATH")
goenv run $*
