#!/bin/sh

# Run BBEdit maketags on Go standard library (exported classes only)

CTAGS=/Applications/BBEdit.app/Contents/Helpers/ctags
TAGFILE="../Completion Data/Go/Go Standard Library.tags"

if [ -d $GOROOT ]; then
    $CTAGS --recurse --langdef=GoStdLib --langmap=GoStdLib:.go \
        --regex-GoStdLib="/func([ \t]+\([^)]+\))?[ \t]+([A-Z][a-zA-Z0-9_]+)/\2/f,func/" \
        --regex-GoStdLib="/var[ \t]+([a-zA-Z_][a-zA-Z0-9_]+)/\1/v,var/" \
        --regex-GoStdLib="/type[ \t]+([a-zA-Z_][a-zA-Z0-9_]+)/\1/t,type/" \
        --languages=GoStdLib -f gostdlib.tags $GOROOT/src/pkg
    if [ -e ./gostdlib.tags ]; then
        mv ./gostdlib.tags "${TAGFILE}"
    fi
fi
